markdown:         kramdown
permalink:        /archives/:title/

title:            "Caturra's Blog"    
description:      "Caturra的个人博客"
highlighter:      rouge
author:
    name:      caturra
    key:       caturra

kramdown:
  math_engine: katex